### ISSUE TITLE
Another videos

### ISSUE THREAD

**Issue by jcubic** [AllThingsSmitty/must-watch-javascript#10]
* Addy Osmani: The Browser Hackers Guide To Instantly Loading Everything | JSConf EU 2017 https://www.youtube.com/watch?v=7vUs5yOuv-o

* Kyle Simpson: Advanced Async and Concurrency Patterns in JavaScript |  JS.LA meetup (date shows 2017) https://www.youtube.com/watch?v=Qg1SvpIau6U

* 10 Things I Regret About Node.js - Ryan Dahl - JSConf EU 2018 https://www.youtube.com/watch?v=M3BM9TB-8yA

**Comment by AllThingsSmitty** [comment]
These are great. Thanks for the suggestions.
