### ISSUE TITLE
Table layout

### ISSUE THREAD

**Issue by AllThingsSmitty** [AllThingsSmitty/must-watch-javascript#11]
I've been thinking about reorganizing the structure of this list into tables for each year. Here's an example:

### 2018
| Talk | Speaker | Event | Time |
|---|---|---|---|
| [**In the Loop**](https://www.youtube.com/watch?v=cCOL7MC4Pl0&list=PLUS3uVC08ZapyqfU21joP-B1vTItKf5qi) | Jake Archibald | JSConf.Asia | 35:11 |
| [**10 Things I Regret About Node.js**](https://www.youtube.com/watch?v=M3BM9TB-8yA&list=PLUS3uVC08ZapyqfU21joP-B1vTItKf5qi) | Ryn Dahl | JSConf.EU | 26:41 |
| [**Deep Learning in JS**](https://www.youtube.com/watch?v=SV-cgdobtTA&list=PLUS3uVC08ZapyqfU21joP-B1vTItKf5qi) | Ashi Krishnan | JSConf.EU | 31:30 |

I'm wondering if this would be an improvement for reviewing. The formatting is much cleaner. Thoughts?

**Comment by AllThingsSmitty** [comment]
I've implemented the table layout, but the table for each year is a different width, as are the columns. Not sure how to resolve that in a uniform way in markdown.

**Comment by mblarsen** [comment]
It doesn't matter that much to me. You kind of focus on year at a time. That is your partition after all.

If you put all in one table you would have an other issue of lots of white space, which makes a row harder to track.

You just cannot win, hahah

**Comment by AllThingsSmitty** [comment]
If I could add <style> to the README, I could resolve this. But it's being parsed as text in the Markdown.

**Comment by AllThingsSmitty** [comment]
I tried this about a year back and the main issue I had was table consistency with each year's videos. I'll keep it as-is for now, it seems to work fine.
