### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by Martin-Pitt** [AllThingsSmitty/must-watch-javascript#4]
Render Conf 2016 was pretty fun and here are their videos: https://vimeo.com/album/3953264

Google I/O this year was ram packed with web goodies, there's just so much, here is the playlist with 171  (!) videos, not all JS specific, but you will be able to find something, surely: https://www.youtube.com/playlist?list=PLOU2XLYxmsILe6_eGvDN3GyiodoV3qNSC

**Comment by AllThingsSmitty** [comment]
@Martin-Pitt thanks, I'll have to check out those links.
